#!/usr/bin/env python

### a temporary db sync script

from ceilometer import storage
from ceilometer.storage import migration
from ceilometer.openstack.common import cfg

#def sync(self, version=None):
#    """Sync the database up to the most recent version."""
#    return migration.db_sync(version)
#
#def version(self):
#    """Print the current database version."""
#    print migration.db_version()

cfg.CONF.database_connection = 'sqlite:///ceilometer.sqlite'
print "CURRENT VERSION: %s" % migration.db_version()
migration.db_sync()
print "UPDATED VERSION: %s" % migration.db_version()
