#!/usr/bin/env python
# -*- encoding: utf-8 -*-
#
# Author: John Tran <jhtran@att.com>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

### a temporary db sync script

from ceilometer import storage
from ceilometer.storage import migration
from ceilometer.openstack.common import cfg

#def sync(self, version=None):
#    """Sync the database up to the most recent version."""
#    return migration.db_sync(version)
#
#def version(self):
#    """Print the current database version."""
#    print migration.db_version()

cfg.CONF.database_connection = 'sqlite:///ceilometer.sqlite'
print "CURRENT VERSION: %s" % migration.db_version()
migration.db_sync()
print "UPDATED VERSION: %s" % migration.db_version()
